version: "3.9"
services:
  app:
    build:
      context: ./api
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /usr/local/bin/app
  db:
    container_name: db
    build: ./docker/db
    ports:
      - "13307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    tty: true
    restart: always
    platform: linux/x86_64
volumes:
  db-data:
