version: "3.9"
services:
  app:
    build:
      context: ./api
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /usr/local/bin/app
  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: passw0rd
      TZ: "Asia/Tokyo"
    ports:
      - 15432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/db:/docker-entrypoint-initdb.d
volumes:
  db-data:
