version: "3"

tasks:
  build:
    desc: 依存関係をインストール.
    cmds:
      - cargo run build

  run:web:
    desc: web 画面を立ち上げる.
    cmds:
      - trunk serve apps/frontend/web/index.html --port 4000 -w apps/frontend/web -w apps/shared -w apps/frontend/package

  run:docs:
    desc: docs を立ち上げる.
    cmds:
      - trunk serve apps/frontend/docs/index.html --port 4002 -w apps/frontend/docs -w apps/shared -w apps/frontend/package

  run:backend:
    desc: API環境を立ち上げる.
    cmds:
      - docker compose up db -d
      - "
        DATABASE_URL=mysql://app_user:app_password@localhost:13307/app \
        cargo watch -s \"cargo run -p apps_backend\"
        "
